coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1% 
        if_not_found: success
        informational: false
    patch:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        informational: false
  ignore:
    - "**/mock/**"
    - "./database/**"
    - "**/mocks/**"
    - "./cmd/**"
    - "./main.go"
    - "./pkg/logger/**"
    - "./pkg/observability/**"
    - "./pkg/resourceful/**"
