// Code generated by MockGen. DO NOT EDIT.
// Source: internal/reimbursement/usecase.go
//
// Generated by this command:
//
//	mockgen -source internal/reimbursement/usecase.go -destination internal/reimbursement/mock/usecase_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/vnnyx/employee-management/internal/auth/entity"
	entity0 "github.com/vnnyx/employee-management/internal/reimbursement/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// SubmitReimbursement mocks base method.
func (m *MockUseCase) SubmitReimbursement(ctx context.Context, authCredential entity.Credential, payload entity0.SubmitReimbursement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitReimbursement", ctx, authCredential, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitReimbursement indicates an expected call of SubmitReimbursement.
func (mr *MockUseCaseMockRecorder) SubmitReimbursement(ctx, authCredential, payload any) *MockUseCaseSubmitReimbursementCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitReimbursement", reflect.TypeOf((*MockUseCase)(nil).SubmitReimbursement), ctx, authCredential, payload)
	return &MockUseCaseSubmitReimbursementCall{Call: call}
}

// MockUseCaseSubmitReimbursementCall wrap *gomock.Call
type MockUseCaseSubmitReimbursementCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUseCaseSubmitReimbursementCall) Return(arg0 error) *MockUseCaseSubmitReimbursementCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUseCaseSubmitReimbursementCall) Do(f func(context.Context, entity.Credential, entity0.SubmitReimbursement) error) *MockUseCaseSubmitReimbursementCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUseCaseSubmitReimbursementCall) DoAndReturn(f func(context.Context, entity.Credential, entity0.SubmitReimbursement) error) *MockUseCaseSubmitReimbursementCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
